# Generated by Django 5.0.6 on 2024-06-06 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Vehicle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "license_number_0",
                    models.CharField(max_length=5, unique=True, verbose_name="차량 앞번호"),
                ),
                (
                    "license_number_1",
                    models.CharField(max_length=5, unique=True, verbose_name="차량 뒷번호"),
                ),
                ("passenger_capacity", models.IntegerField(verbose_name="승차인원")),
                ("release_date", models.DateField(verbose_name="출고일자(연도)")),
                ("vehicle_type", models.CharField(max_length=50, verbose_name="차량종류")),
                ("manufacturer", models.CharField(max_length=50, verbose_name="제조사")),
                ("model_year", models.CharField(max_length=4, verbose_name="모델연도")),
                (
                    "chassis_number",
                    models.CharField(max_length=50, unique=True, verbose_name="차대번호"),
                ),
                ("engine_type", models.CharField(max_length=50, verbose_name="원동기형식")),
                ("driver", models.CharField(max_length=50, verbose_name="담당기사")),
                ("inspection_date", models.DateField(verbose_name="정기점검일")),
                (
                    "usage_status",
                    models.BooleanField(default=False, verbose_name="사용 여부"),
                ),
                (
                    "vehicle_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="차량가격"
                    ),
                ),
                (
                    "plate_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="번호판가격"
                    ),
                ),
                (
                    "insurance_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="보험비"
                    ),
                ),
                (
                    "maintenance_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="정비(월)"
                    ),
                ),
                (
                    "tuning_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="튜닝(일)"
                    ),
                ),
                (
                    "depreciation_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="감가상각(월)"
                    ),
                ),
                (
                    "depreciation_year",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="감가기준년도"
                    ),
                ),
                (
                    "installment_cost",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="할부"
                    ),
                ),
                (
                    "led_display",
                    models.BooleanField(default=False, verbose_name="전광판 유무"),
                ),
                ("karaoke", models.BooleanField(default=False, verbose_name="노래방 유무")),
                (
                    "hot_water_heater",
                    models.BooleanField(default=False, verbose_name="온수기 유무"),
                ),
                (
                    "refrigerator",
                    models.BooleanField(default=False, verbose_name="냉장고 유무"),
                ),
                ("usb", models.BooleanField(default=False, verbose_name="USB")),
                ("tv", models.BooleanField(default=False, verbose_name="TV")),
                ("notes", models.TextField(blank=True, verbose_name="비고")),
            ],
            options={
                "unique_together": {("license_number_0", "license_number_1")},
            },
        ),
        migrations.CreateModel(
            name="VehicleDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document",
                    models.FileField(upload_to="documents/", verbose_name="문서"),
                ),
                (
                    "upload_date",
                    models.DateField(auto_now_add=True, verbose_name="업로드 날짜"),
                ),
                (
                    "vehicle",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="vehicles_app.vehicle",
                        verbose_name="차량",
                    ),
                ),
            ],
        ),
    ]
