# Generated by Django 5.0.6 on 2024-06-06 03:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vehicles_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="insurance_payment_date",
            field=models.DateField(blank=True, null=True, verbose_name="보험 납부일"),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="remaining_installment",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="남은 할부액",
            ),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="type",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="형식"
            ),
        ),
    ]
